name: hostel_management
description: Smart Hostel Management System
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  supabase_flutter: ^2.5.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.67.0
  intl: ^0.19.0
  timeago: ^3.6.1
  uuid: ^4.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  badges: ^3.1.2
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
